### ISSUE TITLE
DNN 9.2.0 - jQuery / Host Setting Tabs Not working

### ISSUE THREAD

**Issue by birksy89** [YAFNET/YAFNET-DNN#47] opened 2018-07-19 16:25 UTC
Hello,

I'm having trouble moving between the tabs in the settings.

I've captured some screenshots of the console when it errors:

![capture2](https://user-images.githubusercontent.com/4971630/42956741-aa749a3a-8b78-11e8-8d1e-d1bf4fb9c8aa.PNG)
![capture](https://user-images.githubusercontent.com/4971630/42956742-aaa0cd6c-8b78-11e8-8602-1d801712a3a4.PNG)

If anyone can help with this, it would be greatly appriciated

Thanks in advance

**Comment by w8tcha** [comment] 2018-07-19 17:07
Its caused by jquery 3. Will be fixed with YAF 2.2.4.13

**Comment by birksy89** [comment] 2018-07-19 17:14
Thanks for the speedy response - This module is required for a client. Can you let me know roughly how long it will take for this release? 

Just so I can set their expectations appropriately 

Thanks again

**Comment by w8tcha** [comment] 2018-07-19 17:31
By the end of the weekend i will release the new version!

**Closed as completed** 2018-07-21 23:28 UTC
Labels: bug

**Comment by birksy89** [comment] 2018-07-23 07:48
Hello, Thanks for sorting this out so quickly!

I might be being daft - But I can't see the new version under the release tab:
https://github.com/YAFNET/YAFNET-DNN/releases

Thanks again for your help

**Comment by w8tcha** [comment] 2018-07-23 08:18
Its the first release on the releases tab!

https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.4.13-5819

**Comment by birksy89** [comment] 2018-07-23 08:35
Morning @w8tcha 

Sorry, I've attached what I can see and it's dated 2017... 

![capture](https://user-images.githubusercontent.com/4971630/43066088-9b9782c6-8e5b-11e8-9bab-2d3807885c40.PNG)

**Comment by w8tcha** [comment] 2018-07-23 08:50
Yes that is correct. Version 2.24.0 was released in 2017. And has been updated to version 2.24.13. github don't show when a release is updated
