### ISSUE TITLE
JQueryUI conflict

### ISSUE THREAD

**Issue by azarbara** [YAFNET/YAFNET-DNN#14] opened 2015-02-22 21:02 UTC
![1](https://cloud.githubusercontent.com/assets/5406334/6320461/6e5e3302-baf3-11e4-99d7-cc19d61304b6.JPG)
as you know the DNN using JqueryUI files and now in the main forum page there is a jquryui.css conflict that shown in the below screenshot. 
is it possible to use dnn hosted files instead of jqueryUI files in YAFNET-DNN?

**Comment by w8tcha** [comment] 2015-02-24 10:10
> is it possible to use dnn hosted files instead of jqueryUI files in YAFNET-DNN?

The problem is that this would break many functions in yaf that need the latest jquery-ui version (dnn always shipping with old versions).

So it would ether break dnn or break the forum, so i have to find a different solution for that issue

**Comment by azarbara** [comment] 2015-02-24 10:45
thanks for your attempts

**Comment by w8tcha** [comment] 2015-02-28 14:45
Looks like this issue is also logged in the dnn bug tracker

https://dnntracker.atlassian.net/browse/DNN-6439

I made a pull request to dnn to fix the modal dialog to make it possible for dnn to use the latest jquery-ui 1.11.x.

https://github.com/dnnsoftware/Dnn.Platform/pull/330

Then this issue can be resolved in YAF

**Comment by azarbara** [comment] 2015-02-28 19:35
Ok,
that's good job.

**Comment by w8tcha** [comment] 2016-03-11 20:35
I think that can be closed. This is already fixed in dnn

**Closed by w8tcha** 2016-03-11 20:35 UTC
